// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC6T_lxIkgsfv9V3wl-K-MOm35K7xEHjg',
    appId: '1:236853421270:android:10bc1c1046bacc6e0d9577',
    messagingSenderId: '236853421270',
    projectId: 'clap-a85c0',
    storageBucket: 'clap-a85c0.appspot.com',
    databaseURL: 'https://clap-a85c0-default-rtdb.firebaseio.com',
    //authDomain: 'clap-a85c0.firebaseapp.com',
    //measurementId: 'G-NPXFJ7L2LB',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsIr8dPm5-M-6YyrOuQlkHZRHtT9uKYvI',
    appId: '1:236853421270:web:3027124c68fd45840d9577',
    messagingSenderId: '236853421270',
    projectId: 'clap-a85c0',
    authDomain: 'clap-a85c0.firebaseapp.com',
    storageBucket: 'keep-notes-df6da.appspot.com',
    measurementId: 'G-NPXFJ7L2LB',
  );
}
